from PyQt5 import QtCore, QtGui, QtWidgets
# import res_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(900, 900)
        MainWindow.setMaximumSize(QtCore.QSize(900, 900))
        MainWindow.setAutoFillBackground(False)

        MainWindow.setStyleSheet('background-image: ./static/img/vm.png;')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet('')
        self.centralwidget.setObjectName('centralwidget')
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 901, 51))
        self.title.setStyleSheet('')
        self.title.setObjectName('title')
        self.product_choice = QtWidgets.QWidget(self.centralwidget)
        self.product_choice.setGeometry(QtCore.QRect(40, 210, 121, 131))
        self.product_choice.setStyleSheet('background-color: rgb(0, 152, 116);')
        self.product_choice.setObjectName('product_choice')
        self.product_place_choice = QtWidgets.QLineEdit(self.product_choice)
        self.product_place_choice.setGeometry(QtCore.QRect(20, 10, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.product_place_choice.setFont(font)
        self.product_place_choice.setStyleSheet('')
        self.product_place_choice.setAlignment(QtCore.Qt.AlignCenter)
        self.product_place_choice.setObjectName('product_place_choice')
        self.buy_product = QtWidgets.QPushButton(self.product_choice)
        self.buy_product.setGeometry(QtCore.QRect(20, 80, 81, 32))
        self.buy_product.setStyleSheet('')
        self.buy_product.setObjectName('buy_product')
        self.plus_product = QtWidgets.QLabel(self.centralwidget)
        self.plus_product.setGeometry(QtCore.QRect(750, 60, 131, 21))
        self.plus_product.setStyleSheet('')
        self.plus_product.setObjectName('plus_product')
        self.add_product = QtWidgets.QWidget(self.centralwidget)
        self.add_product.setGeometry(QtCore.QRect(740, 80, 151, 321))
        self.add_product.setStyleSheet('')
        self.add_product.setObjectName('add_product')
        self.product_price_num = QtWidgets.QSpinBox(self.add_product)
        self.product_price_num.setGeometry(QtCore.QRect(80, 100, 61, 20))
        self.product_price_num.setStyleSheet('')
        self.product_price_num.setObjectName('product_price_num')
        self.product_list = QtWidgets.QListWidget(self.add_product)
        self.product_list.setGeometry(QtCore.QRect(10, 10, 131, 81))
        self.product_list.setStyleSheet('background-color: rgb(0, 152, 116);')
        self.product_list.setObjectName('product_list')
        item = QtWidgets.QListWidgetItem()
        self.product_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.product_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.product_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.product_list.addItem(item)
        self.product_price_label = QtWidgets.QLabel(self.add_product)
        self.product_price_label.setGeometry(QtCore.QRect(10, 100, 60, 16))
        self.product_price_label.setStyleSheet('')
        self.product_price_label.setObjectName('product_price_label')
        self.product_quantity_label = QtWidgets.QLabel(self.add_product)
        self.product_quantity_label.setGeometry(QtCore.QRect(10, 130, 60, 16))
        self.product_quantity_label.setStyleSheet('')
        self.product_quantity_label.setObjectName('product_quantity_label')
        self.product_quantity_num = QtWidgets.QSpinBox(self.add_product)
        self.product_quantity_num.setGeometry(QtCore.QRect(80, 130, 61, 20))
        self.product_quantity_num.setStyleSheet('')
        self.product_quantity_num.setObjectName('product_quantity_num')
        self.product_name = QtWidgets.QLineEdit(self.add_product)
        self.product_name.setGeometry(QtCore.QRect(10, 160, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.product_name.setFont(font)
        self.product_name.setStyleSheet('background-color: rgb(0, 152, 116);')
        self.product_name.setAlignment(QtCore.Qt.AlignCenter)
        self.product_name.setObjectName('product_name')
        self.product_maker = QtWidgets.QLineEdit(self.add_product)
        self.product_maker.setGeometry(QtCore.QRect(10, 190, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.product_maker.setFont(font)
        self.product_maker.setStyleSheet('background-color: rgb(0, 152, 116);')
        self.product_maker.setAlignment(QtCore.Qt.AlignCenter)
        self.product_maker.setObjectName('product_maker')
        self.product_set_place = QtWidgets.QLineEdit(self.add_product)
        self.product_set_place.setGeometry(QtCore.QRect(30, 220, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.product_set_place.setFont(font)
        self.product_set_place.setStyleSheet('background-color: rgb(0, 152, 116);')
        self.product_set_place.setAlignment(QtCore.Qt.AlignCenter)
        self.product_set_place.setObjectName('product_set_place')
        self.product_add_buttom = QtWidgets.QPushButton(self.add_product)
        self.product_add_buttom.setGeometry(QtCore.QRect(30, 250, 91, 32))
        self.product_add_buttom.setStyleSheet('background-color: rgb(0, 152, 116);')
        self.product_add_buttom.setObjectName('product_add_buttom')
        self.product_add_result = QtWidgets.QLabel(self.add_product)
        self.product_add_result.setGeometry(QtCore.QRect(10, 290, 131, 21))
        self.product_add_result.setStyleSheet('')
        self.product_add_result.setObjectName('product_add_result')
        self.drinks_place_num_label = QtWidgets.QLabel(self.centralwidget)
        self.drinks_place_num_label.setGeometry(QtCore.QRect(40, 190, 121, 16))
        self.drinks_place_num_label.setStyleSheet('')
        self.drinks_place_num_label.setObjectName('drinks_place_num_label')
        self.place_num_3 = QtWidgets.QLabel(self.centralwidget)
        self.place_num_3.setGeometry(QtCore.QRect(40, 380, 121, 31))
        self.place_num_3.setStyleSheet('')
        self.place_num_3.setObjectName('place_num_3')
        self.drinks_choice = QtWidgets.QWidget(self.centralwidget)
        self.drinks_choice.setGeometry(QtCore.QRect(40, 415, 121, 151))
        self.drinks_choice.setStyleSheet('background-color: rgb(0, 152, 116);')
        self.drinks_choice.setObjectName('drinks_choice')
        self.drinks_place_choice = QtWidgets.QLineEdit(self.drinks_choice)
        self.drinks_place_choice.setGeometry(QtCore.QRect(20, 10, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.drinks_place_choice.setFont(font)
        self.drinks_place_choice.setStyleSheet('')
        self.drinks_place_choice.setAlignment(QtCore.Qt.AlignCenter)
        self.drinks_place_choice.setObjectName('drinks_place_choice')
        self.buy_drinks = QtWidgets.QPushButton(self.drinks_choice)
        self.buy_drinks.setGeometry(QtCore.QRect(20, 80, 81, 32))
        self.buy_drinks.setStyleSheet('')
        self.buy_drinks.setObjectName('buy_drinks')
        self.plus_drink = QtWidgets.QLabel(self.centralwidget)
        self.plus_drink.setGeometry(QtCore.QRect(750, 410, 131, 21))
        self.plus_drink.setStyleSheet('')
        self.plus_drink.setObjectName('plus_drink')
        self.add_drinks = QtWidgets.QWidget(self.centralwidget)
        self.add_drinks.setGeometry(QtCore.QRect(740, 430, 151, 261))
        self.add_drinks.setStyleSheet('')
        self.add_drinks.setObjectName('add_drinks')
        self.drinks_price_num = QtWidgets.QSpinBox(self.add_drinks)
        self.drinks_price_num.setGeometry(QtCore.QRect(80, 80, 61, 20))
        self.drinks_price_num.setStyleSheet('')
        self.drinks_price_num.setObjectName('drinks_price_num')
        self.drinks_list = QtWidgets.QListWidget(self.add_drinks)
        self.drinks_list.setGeometry(QtCore.QRect(10, 10, 131, 61))
        self.drinks_list.setStyleSheet('background-color: rgb(0, 152, 116);')
        self.drinks_list.setObjectName('drinks_list')
        item = QtWidgets.QListWidgetItem()
        self.drinks_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.drinks_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.drinks_list.addItem(item)
        self.drinks_price_label = QtWidgets.QLabel(self.add_drinks)
        self.drinks_price_label.setGeometry(QtCore.QRect(10, 80, 60, 16))
        self.drinks_price_label.setStyleSheet('')
        self.drinks_price_label.setObjectName('drinks_price_label')
        self.drinks_quantity_label = QtWidgets.QLabel(self.add_drinks)
        self.drinks_quantity_label.setGeometry(QtCore.QRect(10, 110, 60, 16))
        self.drinks_quantity_label.setStyleSheet('')
        self.drinks_quantity_label.setObjectName('drinks_quantity_label')
        self.drinks_quantity_num = QtWidgets.QSpinBox(self.add_drinks)
        self.drinks_quantity_num.setGeometry(QtCore.QRect(80, 110, 61, 20))
        self.drinks_quantity_num.setStyleSheet('')
        self.drinks_quantity_num.setObjectName('drinks_quantity_num')
        self.drinks_set_place = QtWidgets.QLineEdit(self.add_drinks)
        self.drinks_set_place.setGeometry(QtCore.QRect(30, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.drinks_set_place.setFont(font)
        self.drinks_set_place.setStyleSheet('background-color: rgb(0, 152, 116);')
        self.drinks_set_place.setAlignment(QtCore.Qt.AlignCenter)
        self.drinks_set_place.setObjectName('drinks_set_place')
        self.drinks_add_buttom = QtWidgets.QPushButton(self.add_drinks)
        self.drinks_add_buttom.setGeometry(QtCore.QRect(30, 190, 91, 32))
        self.drinks_add_buttom.setStyleSheet('background-color: rgb(0, 152, 116);')
        self.drinks_add_buttom.setObjectName('drinks_add_buttom')
        self.drinks_add_result = QtWidgets.QLabel(self.add_drinks)
        self.drinks_add_result.setGeometry(QtCore.QRect(10, 230, 131, 21))
        self.drinks_add_result.setStyleSheet('')
        self.drinks_add_result.setObjectName('drinks_add_result')
        self.payments = QtWidgets.QWidget(self.centralwidget)
        self.payments.setGeometry(QtCore.QRect(600, 510, 111, 131))
        self.payments.setStyleSheet('background-color: rgb(0, 152, 116);')
        self.payments.setObjectName('payments')
        self.add_coins_5 = QtWidgets.QPushButton(self.payments)
        self.add_coins_5.setGeometry(QtCore.QRect(20, 70, 71, 21))
        self.add_coins_5.setStyleSheet('')
        self.add_coins_5.setObjectName('add_coins_5')
        self.add_coins_10 = QtWidgets.QPushButton(self.payments)
        self.add_coins_10.setGeometry(QtCore.QRect(20, 40, 71, 21))
        self.add_coins_10.setStyleSheet('')
        self.add_coins_10.setObjectName('add_coins_10')
        self.amount_paid = QtWidgets.QLabel(self.payments)
        self.amount_paid.setGeometry(QtCore.QRect(0, 10, 111, 20))
        self.amount_paid.setStyleSheet('')
        self.amount_paid.setObjectName('amount_paid')
        self.add_coins_6 = QtWidgets.QPushButton(self.payments)
        self.add_coins_6.setGeometry(QtCore.QRect(20, 100, 71, 21))
        self.add_coins_6.setStyleSheet('')
        self.add_coins_6.setObjectName('add_coins_6')
        self.buy_result = QtWidgets.QLabel(self.centralwidget)
        self.buy_result.setGeometry(QtCore.QRect(350, 620, 151, 41))
        self.buy_result.setStyleSheet('')
        self.buy_result.setObjectName('buy_result')
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName('statusbar')
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate('MainWindow', 'Vending Machine'))
        self.title.setText(_translate('MainWindow', '<html><head/><body><p align=\'center\'><span style=\' font-size:18pt; font-weight:600;\'>Аппарат по продаже Напитков и Снеков</span></p></body></html>'))
        self.product_place_choice.setText(_translate('MainWindow', '00'))
        self.buy_product.setText(_translate('MainWindow', 'Купить'))
        self.plus_product.setText(_translate('MainWindow', '<html><head/><body><p align=\'center\'>Добавить продукты</p></body></html>'))
        __sortingEnabled = self.product_list.isSortingEnabled()
        self.product_list.setSortingEnabled(False)
        item = self.product_list.item(0)
        item.setText(_translate('MainWindow', 'Печень'))
        item = self.product_list.item(1)
        item.setText(_translate('MainWindow', 'Чипсы'))
        item = self.product_list.item(2)
        item.setText(_translate('MainWindow', 'Шоколад'))
        item = self.product_list.item(3)
        item.setText(_translate('MainWindow', 'Напитки бут'))
        self.product_list.setSortingEnabled(__sortingEnabled)
        self.product_price_label.setText(_translate('MainWindow', 'Цена'))
        self.product_quantity_label.setText(_translate('MainWindow', 'Кол-во'))
        self.product_name.setText(_translate('MainWindow', 'Название продукта'))
        self.product_maker.setText(_translate('MainWindow', 'Фирма'))
        self.product_set_place.setText(_translate('MainWindow', 'МЕСТО №'))
        self.product_add_buttom.setText(_translate('MainWindow', 'Добавить'))
        self.product_add_result.setText(_translate('MainWindow', '<html><head/><body><p align=\'center\'><br/></p></body></html>'))
        self.drinks_place_num_label.setText(_translate('MainWindow', '<html><head/><body><p align=\'center\'>Ввод номера</p></body></html>'))
        self.place_num_3.setText(_translate('MainWindow', '<html><head/><body><p align=\'center\'>Выбор горячего <br/>напитка</p></body></html>'))
        self.drinks_place_choice.setText(_translate('MainWindow', '00'))
        self.buy_drinks.setText(_translate('MainWindow', 'Купить'))
        self.plus_drink.setText(_translate('MainWindow', '<html><head/><body><p align=\'center\'>Добавить напитки</p></body></html>'))
        __sortingEnabled = self.drinks_list.isSortingEnabled()
        self.drinks_list.setSortingEnabled(False)
        item = self.drinks_list.item(0)
        item.setText(_translate('MainWindow', 'Кофе'))
        item = self.drinks_list.item(1)
        item.setText(_translate('MainWindow', 'Чай'))
        item = self.drinks_list.item(2)
        item.setText(_translate('MainWindow', 'Горячий шок'))
        self.drinks_list.setSortingEnabled(__sortingEnabled)
        self.drinks_price_label.setText(_translate('MainWindow', 'Цена'))
        self.drinks_quantity_label.setText(_translate('MainWindow', 'Кол-во'))
        self.drinks_set_place.setText(_translate('MainWindow', 'МЕСТО №'))
        self.drinks_add_buttom.setText(_translate('MainWindow', 'Добавить'))
        self.drinks_add_result.setText(_translate('MainWindow', '<html><head/><body><p align=\'center\'><br/></p></body></html>'))
        self.add_coins_5.setText(_translate('MainWindow', '+5 монет'))
        self.add_coins_10.setText(_translate('MainWindow', '+10 монет'))
        self.amount_paid.setText(_translate('MainWindow', '<html><head/><body><p align=\'center\'>Монет: 0</p></body></html>'))
        self.add_coins_6.setText(_translate('MainWindow', 'Сброс'))
        self.buy_result.setText(_translate('MainWindow', '<html><head/><body><p align=\'center\'><br/></p></body></html>'))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
